tidb:
  addr: 127.0.0.1:4000
  user: root
  password: ""
  dbName: "tpch_0_1"

load:
  needLoadData: true
  scale: "0.1"
  table: all

check:
  interval: 60
  timeout: 1000

autoscale:
  enableAutoScale: true
  tidbClusterID: t1
  httpServerAddr: http://tiflash-autoscale-lb.tiflash-autoscale.svc.cluster.local:8081

workload:
  pauseResumeTest:
    queryCount: 100
    threadNum: 2
  scaleOutTest:
    queryCount: 2000
    threadNum: 50
  scaleInTest:
    queryCount: 300
    threadNum: 1