tidb:
  addr: 127.0.0.1:4000
  user: root
  password: ""

load:
  needLoadData: true
  scale: "0.1"
  table: all

check:
  interval: 10
  timeout: 300

autoscale:
  enableAutoScale: true
  tidbClusterID: t1
  httpServerAddr: http://tiflash-autoscale-lb.tiflash-autoscale.svc.cluster.local:8081

workload:
  round1:
    queryCount: 500
    threadNum: 2
  round2:
    queryCount: 5000
    threadNum: 50
  round3:
    queryCount: 500
    threadNum: 2