[storage]
enable-ttl = true
api-version = 2

[dfs]
prefix = "local-cluster"
s3-endpoint = "http://127.0.0.1:19000"
s3-key-id = "minioadmin"
s3-secret-key = "minioadmin"
s3-bucket = "cse"
s3-region = "local"
