SELECT
	L_SHIPMODE,
	SUM(CASE
			WHEN O_ORDERPRIORITY = '1-URGENT'
			OR O_ORDERPRIORITY = '2-HIGH'
			THEN 1
			ELSE 0
	END) AS HIGH_LINE_COUNT,
	SUM(CASE
			WHEN O_ORDERPRIORITY <> '1-URGENT'
			AND O_ORDERPRIORITY <> '2-HIGH'
			THEN 1
			ELSE 0
	END) AS LOW_LINE_COUNT
FROM
	orders,
	lineitem
WHERE
	O_ORDERKEY = L_ORDERKEY
	AND L_SHIPMODE IN ('RAIL', 'FOB')
	AND L_COMMITDATE < L_RECEIPTDATE
	AND L_SHIPDATE < L_COMMITDATE
	AND L_RECEIPTDATE >= DATE '1997-01-01'
	AND L_RECEIPTDATE < DATE '1998-01-01'
GROUP BY
	L_SHIPMODE
ORDER BY
	L_SHIPMODE
