SELECT
	O_ORDERPRIORITY,
	COUNT(*) AS ORDER_COUNT
FROM
	orders
WHERE
	O_ORDERDATE >= DATE '1995-01-01'
	AND O_ORDERDATE < DATE '1995-04-01'
	AND EXISTS (
		SELECT
			*
		FROM
			lineitem
		WHERE
			L_ORDERKEY = O_ORDERKEY
			AND L_COMMITDATE < L_RECEIPTDATE
		)
GROUP BY
	O_ORDERPRIORITY
ORDER BY
	O_ORDERPRIORITY
